export const books = [
    { isChosen: false, name: 'piancil', key: 1, uid: 'GTOZSmwcIhYOdFvZKzJj', isPickup: false },
    { name: 'paikhiatna', isChosen: false, key: 2, uid: 'QNVsKOQzZytvVtZ', isPickup: false },
    { name: 'siampi laibu', isChosen: false, key: 3, uid: 'BZAsEuyivjdfvVAWir', isPickup: false },
    { name: 'gamlak vakna', isChosen: false, key: 4, uid: 'vhunmzzHwaTmmAGY', isPickup: false },
    { isChosen: false, name: 'thu-hilh kikna', key: 5, uid: 'fPqpGTgvKslZNpfC', isPickup: false },
    { isChosen: false, name: 'joshua', key: 6, uid: 'uowNVPlJvfeNYfpj', isPickup: false },
    { name: 'thukhente', isChosen: false, key: 7, uid: 'vxKBbpDwTdffypZQo', isPickup: false },
    { name: 'ruth', isChosen: false, key: 8, uid: 'XLbWmOSDpijeBdRwLe', isPickup: false },
    { name: 'samuel masa', isChosen: false, key: 9, uid: 'jJQxKLQwvDrtBzXl', isPickup: false },
    { name: 'samuel nihna', isChosen: false, key: 10, uid: 'QrKZnhtRJbQrveHndl', isPickup: false },
    { isChosen: false, name: 'kumpite masa', key: 11, uid: 'qaLxEWFQpbCDDsZAt', isPickup: false },
    { name: 'kumpite nihna', isChosen: false, key: 12, uid: 'okPmBJJLrmIqxNauJJ', isPickup: false },
    { isChosen: false, name: 'khang-tangthu masa', key: 13, uid: 'qNsfAWmcABzEPyMw', isPickup: false },
    { name: 'khang-tangthu nihna', isChosen: false, key: 14, uid: 'IgMqrMvSVCLNdyFPwDnS', isPickup: false },
    { isChosen: false, name: 'nehemiah', key: 15, uid: 'zvsEfbbJjyRJIBcgwU', isPickup: false },
    { name: 'ezra', isChosen: false, key: 16, uid: 'wCiYokVouzqFQQIh', isPickup: false },
    { isChosen: false, name: 'esther', key: 17, uid: 'XirKzWIZjyLtVflGP', isPickup: false },
    { isChosen: false, name: 'job', key: 18, uid: 'oaFWUKZsWvlVoOeC', isPickup: false },
    { name: 'late', isChosen: false, key: 19, uid: 'huZjRfTTVWfRWGAUv', isPickup: false },
    { isChosen: false, name: 'paunak', key: 20, uid: 'zMUrahZuoognHhNrOI', isPickup: false },
    { name: 'thuhilhsia', isChosen: false, key: 21, uid: 'tDSmrTwCLIBCxEz', isPickup: false },
    { name: 'solomon la', isChosen: false, key: 22, uid: 'mXldwejVCmwjZwhnHxz', isPickup: false },
    { name: 'isaiah', isChosen: false, key: 23, uid: 'VlUGXGlvAMaWTQE', isPickup: false },
    { isChosen: false, name: 'jeremiah', key: 24, uid: 'QdIahZptpNAiIpKtXp', isPickup: false },
    { isChosen: false, name: 'kahla', key: 25, uid: 'yiwCzApKuYKluLkpXCeK', isPickup: false },
    { name: 'ezekiel', isChosen: false, key: 26, uid: 'XdRrtQDJVvdFfKrAZ', isPickup: false },
    { name: 'daniel', isChosen: false, key: 27, uid: 'dggoruJcvlCvpt', isPickup: false },
    { name: 'hosea', isChosen: false, key: 28, uid: 'kWFMXgZyYNILGY', isPickup: false },
    { name: 'joel', isChosen: false, key: 29, uid: 'QstETsHNpOWfIkAv', isPickup: false },
    { isChosen: false, name: 'amos', key: 30, uid: 'PajkYvyMvzvhpRLAi', isPickup: false },
    { isChosen: false, name: 'obdiah', key: 31, uid: 'HeWuKSLfrdTStqJL', isPickup: false },
    { isChosen: false, name: 'jonah', key: 32, uid: 'IOjIyRjjGyoiwIjy', isPickup: false },
    { name: 'mikah', isChosen: false, key: 33, uid: 'DAvLHHppuHbwsumAu', isPickup: false },
    { name: 'nahum', isChosen: false, key: 34, uid: 'CrvbXqmtEHTmCzPX', isPickup: false },
    { name: 'habakkuk', isChosen: false, key: 35, uid: 'vBOvEvzJpjfUjxvZ', isPickup: false },
    { isChosen: false, name: 'zefaniah', key: 36, uid: 'OpyKCTgeDCVUKCQBJ', isPickup: false },
    { isChosen: false, name: 'haggai', key: 37, uid: 'hQwJblMcFMrnYFJTQ', isPickup: false },
    { name: 'zekhariah', isChosen: false, key: 38, uid: 'oHqLxlxkTEPKQTnyA', isPickup: false },
    { isChosen: false, name: 'malakhi', key: 39, uid: 'ZXbTKEdJitIXhQVQEcq', isPickup: false },
    { isChosen: false, name: 'matthai', key: 40, uid: 'ETDWwEHeiWmgTpmzon', isPickup: false },
    { isChosen: false, name: 'marka', key: 41, uid: 'FeAIYGnMkZxDGGyjM', isPickup: false },
    { isChosen: false, name: 'luka', key: 42, uid: 'WCdVdbtygJRTCeJz', isPickup: false },
    { isChosen: false, name: 'johan', key: 43, uid: 'FExJqUmiUYStYnlG', isPickup: false },
    { name: 'sawltak', isChosen: false, key: 44, uid: 'MepufRWjelHJtnQms', isPickup: false },
    { name: 'rom', isChosen: false, key: 45, uid: 'PqTqCGkXkqyuew', isPickup: false },
    { isChosen: false, name: 'korin masa', key: 46, uid: 'VUlVdrjKZdfcK', isPickup: false },
    { name: 'korin nihna', isChosen: false, key: 47, uid: 'xsOvylGNZdTUcnJM', isPickup: false },
    { name: 'galati', isChosen: false, key: 48, uid: 'wiYNpNPlqojFqqtUN', isPickup: false },
    { name: 'efesa', isChosen: false, key: 49, uid: 'feongpFzdBULnUYUVQ', isPickup: false },
    { name: 'filippi', isChosen: false, key: 50, uid: 'RSJqRYdZleNnJirSzm', isPickup: false },
    { name: 'kolose', isChosen: false, key: 51, uid: 'WskAxyamzmEMAUYrmb', isPickup: false },
    { isChosen: false, name: 'thesalon masa', key: 52, uid: 'zcXxdreaquBOyFEW', isPickup: false },
    { name: 'thesalon nihna', isChosen: false, key: 53, uid: 'BjuugJUiWSESexNS', isPickup: false },
    { name: 'timoti masa', isChosen: false, key: 54, uid: 'cRbXGpmLpURtQlLLN', isPickup: false },
    { name: 'timoti nihna', isChosen: false, key: 55, uid: 'euUWpFTnDHTRSmbHt', isPickup: false },
    { isChosen: false, name: 'titu', key: 56, uid: 'PDfttpgRhjvUdolRDEE', isPickup: false },
    { name: 'filemon', isChosen: false, key: 57, uid: 'OWrAJFHkylWYmutMy', isPickup: false },
    { isChosen: false, name: 'hebru', key: 58, uid: 'TCPPxvPoDZsSiHtYDi', isPickup: false },
    { name: 'jeim', isChosen: false, key: 59, uid: 'FaOGhVuHftwOeQWeVy', isPickup: false },
    { isChosen: false, name: 'piter masa', key: 60, uid: 'MlhhTGqSkPkXStRUoz', isPickup: false },
    { name: 'piter nihna', isChosen: false, key: 61, uid: 'QtqBQiTwYNypnPUXg', isPickup: false },
    { isChosen: false, name: 'johan masa', key: 62, uid: 'HuEZrfYfNWiKMCerPc', isPickup: false },
    { isChosen: false, name: 'johan nihna', key: 63, uid: 'BnfSaeEAcIWQkSpqO', isPickup: false },
    { isChosen: false, name: 'john thumna', key: 64, uid: 'tpsvChzqzaHpBOl', isPickup: false },
    { name: 'juda', isChosen: false, key: 65, uid: 'cwfIDbnNazdBDRvijgSa', isPickup: false },
    { isChosen: false, name: 'mangmuhna', key: 66, uid: 'koDqLqyToaVpBsvjr', isPickup: false },
]