export const books = [
    { name: 'late', isChosen: false, key: 19, uid: 'huZjRfTTVWfRWGAUv', isPickup: false },
    { isChosen: false, name: 'malakhi', key: 39, uid: 'ZXbTKEdJitIXhQVQEcq', isPickup: false },
    { isChosen: false, name: 'matthai', key: 40, uid: 'ETDWwEHeiWmgTpmzon', isPickup: false },
    { isChosen: false, name: 'marka', key: 41, uid: 'FeAIYGnMkZxDGGyjM', isPickup: false },
    { isChosen: false, name: 'luka', key: 42, uid: 'WCdVdbtygJRTCeJz', isPickup: false },
    { isChosen: false, name: 'johan', key: 43, uid: 'FExJqUmiUYStYnlG', isPickup: false },
    { name: 'sawltak', isChosen: false, key: 44, uid: 'MepufRWjelHJtnQms', isPickup: false },
    { name: 'rom', isChosen: false, key: 45, uid: 'PqTqCGkXkqyuew', isPickup: false },
    { isChosen: false, name: 'korin masa', key: 46, uid: 'VUlVdrjKZdfcK', isPickup: false },
    { name: 'korin nihna', isChosen: false, key: 47, uid: 'xsOvylGNZdTUcnJM', isPickup: false },
    { name: 'galati', isChosen: false, key: 48, uid: 'wiYNpNPlqojFqqtUN', isPickup: false },
    { name: 'efesa', isChosen: false, key: 49, uid: 'feongpFzdBULnUYUVQ', isPickup: false },
    { name: 'filippi', isChosen: false, key: 50, uid: 'RSJqRYdZleNnJirSzm', isPickup: false },
    { name: 'kolose', isChosen: false, key: 51, uid: 'WskAxyamzmEMAUYrmb', isPickup: false },
    { isChosen: false, name: 'thesalon masa', key: 52, uid: 'zcXxdreaquBOyFEW', isPickup: false },
    { name: 'thesalon nihna', isChosen: false, key: 53, uid: 'BjuugJUiWSESexNS', isPickup: false },
    { name: 'timoti masa', isChosen: false, key: 54, uid: 'cRbXGpmLpURtQlLLN', isPickup: false },
    { name: 'timoti nihna', isChosen: false, key: 55, uid: 'euUWpFTnDHTRSmbHt', isPickup: false },
    { isChosen: false, name: 'titu', key: 56, uid: 'PDfttpgRhjvUdolRDEE', isPickup: false },
    { name: 'filemon', isChosen: false, key: 57, uid: 'OWrAJFHkylWYmutMy', isPickup: false },
    { isChosen: false, name: 'hebru', key: 58, uid: 'TCPPxvPoDZsSiHtYDi', isPickup: false },
    { name: 'jeim', isChosen: false, key: 59, uid: 'FaOGhVuHftwOeQWeVy', isPickup: false },
    { isChosen: false, name: 'piter masa', key: 60, uid: 'MlhhTGqSkPkXStRUoz', isPickup: false },
    { name: 'piter nihna', isChosen: false, key: 61, uid: 'QtqBQiTwYNypnPUXg', isPickup: false },
    { isChosen: false, name: 'johan masa', key: 62, uid: 'HuEZrfYfNWiKMCerPc', isPickup: false },
    { isChosen: false, name: 'johan nihna', key: 63, uid: 'BnfSaeEAcIWQkSpqO', isPickup: false },
    { isChosen: false, name: 'john thumna', key: 64, uid: 'tpsvChzqzaHpBOl', isPickup: false },
    { name: 'juda', isChosen: false, key: 65, uid: 'cwfIDbnNazdBDRvijgSa', isPickup: false },
    { isChosen: false, name: 'mangmuhna', key: 66, uid: 'koDqLqyToaVpBsvjr', isPickup: false },
]