export const books = [
    { name: 'kumpite nihna', isChosen: false, key: 'okPmBJJLrmIqxNauJJ', isPickup: false },
    { isChosen: false, name: 'titu', key: 'PDfttpgRhjvUdolRDEE', isPickup: false },
    { name: 'daniel', isChosen: false, key: 'dggoruJcvlCvpt', isPickup: false },
    { isChosen: false, name: 'mangmuhna', key: 'koDqLqyToaVpBsvjr', isPickup: false },
    { name: 'samuel masa', isChosen: false, key: 'jJQxKLQwvDrtBzXl', isPickup: false },
    { isChosen: false, name: 'luka', key: 'WCdVdbtygJRTCeJz', isPickup: false },
    { isChosen: false, name: 'khang-tangthu masa', key: 'qNsfAWmcABzEPyMw', isPickup: false },
    { name: 'habakkuk', isChosen: false, key: 'vBOvEvzJpjfUjxvZ', isPickup: false },
    { name: 'siampi laibu', isChosen: false, key: 'BZAsEuyivjdfvVAWir', isPickup: false },
    { name: 'thesalon nihna', isChosen: false, key: 'BjuugJUiWSESexNS', isPickup: false },
    { isChosen: false, name: 'johan nihna', key: 'BnfSaeEAcIWQkSpqO', isPickup: false },
    { name: 'nahum', isChosen: false, key: 'CrvbXqmtEHTmCzPX', isPickup: false },
    { name: 'mikah', isChosen: false, key: 'DAvLHHppuHbwsumAu', isPickup: false },
    { isChosen: false, name: 'matthai', key: 'ETDWwEHeiWmgTpmzon', isPickup: false },
    { isChosen: false, name: 'johan', key: 'FExJqUmiUYStYnlG', isPickup: false },
    { name: 'james', isChosen: false, key: 'FaOGhVuHftwOeQWeVy', isPickup: false },
    { isChosen: false, name: 'marka', key: 'FeAIYGnMkZxDGGyjM', isPickup: false },
    { isChosen: false, name: '"piancil"', key: 'GTOZSmwcIhYOdFvZKzJj', isPickup: false },
    { isChosen: false, name: 'obdiah', key: 'HeWuKSLfrdTStqJL', isPickup: false },
    { isChosen: false, name: 'johan masa', key: 'HuEZrfYfNWiKMCerPc', isPickup: false },
    { isChosen: false, name: 'jonah', key: 'IOjIyRjjGyoiwIjy', isPickup: false },
    { name: 'khang-tangthu nihna', isChosen: false, key: 'IgMqrMvSVCLNdyFPwDnS', isPickup: false },
    { name: 'sawltak', isChosen: false, key: 'MepufRWjelHJtnQms', isPickup: false },
    { isChosen: false, name: 'piter masa', key: 'MlhhTGqSkPkXStRUoz', isPickup: false },
    { name: 'filemon', isChosen: false, key: 'OWrAJFHkylWYmutMy', isPickup: false },
    { isChosen: false, name: 'zefaniah', key: 'OpyKCTgeDCVUKCQBJ', isPickup: false },
    { isChosen: false, name: 'amos', key: 'PajkYvyMvzvhpRLAi', isPickup: false },
    { name: 'rom', isChosen: false, key: 'PqTqCGkXkqyuew', isPickup: false },
    { name: 'paikhiatna', isChosen: false, key: 'QNVsKOQzZytvVtZ', isPickup: false },
    { isChosen: false, name: 'jeremiah', key: 'QdIahZptpNAiIpKtXp', isPickup: false },
    { name: 'samuel nihna', isChosen: false, key: 'QrKZnhtRJbQrveHndl', isPickup: false },
    { name: 'joel', isChosen: false, key: 'QstETsHNpOWfIkAv', isPickup: false },
    { name: 'piter nihna', isChosen: false, key: 'QtqBQiTwYNypnPUXg', isPickup: false },
    { name: 'filippi', isChosen: false, key: 'RSJqRYdZleNnJirSzm', isPickup: false },
    { isChosen: false, name: 'hebru', key: 'TCPPxvPoDZsSiHtYDi', isPickup: false },
    { isChosen: false, name: 'korin masa', key: 'VUlVdrjKZdfcK', isPickup: false },
    { name: 'isaiah', isChosen: false, key: 'VlUGXGlvAMaWTQE', isPickup: false },
    { name: 'kolose', isChosen: false, key: 'WskAxyamzmEMAUYrmb', isPickup: false },
    { name: 'ruth', isChosen: false, key: 'XLbWmOSDpijeBdRwLe', isPickup: false },
    { name: 'ezekiel', isChosen: false, key: 'XdRrtQDJVvdFfKrAZ', isPickup: false },
    { isChosen: false, name: 'esther', key: 'XirKzWIZjyLtVflGP', isPickup: false },
    { isChosen: false, name: 'malakhi', key: 'ZXbTKEdJitIXhQVQEcq', isPickup: false },
    { name: 'timoti masa', isChosen: false, key: 'cRbXGpmLpURtQlLLN', isPickup: false },
    { name: 'juda', isChosen: false, key: 'cwfIDbnNazdBDRvijgSa', isPickup: false },
    { name: 'timoti nihna', isChosen: false, key: 'euUWpFTnDHTRSmbHt', isPickup: false },
    { isChosen: false, name: 'thu-hilh kikna', key: 'fPqpGTgvKslZNpfC', isPickup: false },
    { name: 'efesa', isChosen: false, key: 'feongpFzdBULnUYUVQ', isPickup: false },
    { isChosen: false, name: 'haggai', key: 'hQwJblMcFMrnYFJTQ', isPickup: false },
    { name: 'late', isChosen: false, key: 'huZjRfTTVWfRWGAUv', isPickup: false },
    { name: 'hosea', isChosen: false, key: 'kWFMXgZyYNILGY', isPickup: false },
    { name: 'solomon la', isChosen: false, key: 'mXldwejVCmwjZwhnHxz', isPickup: false },
    { isChosen: false, "name ": 'job', key: 'oaFWUKZsWvlVoOeC', isPickup: false },
    { name: 'zekhariah', isChosen: false, key: 'oHqLxlxkTEPKQTnyA', isPickup: false },
    { isChosen: false, name: 'kumpite masa', key: 'qaLxEWFQpbCDDsZAt', isPickup: false },
    { name: 'thuhilhsia', isChosen: false, key: 'tDSmrTwCLIBCxEz', isPickup: false },
    { isChosen: false, name: 'john thumna', key: 'tpsvChzqzaHpBOl', isPickup: false },
    { isChosen: false, name: 'joshua', key: 'uowNVPlJvfeNYfpj', isPickup: false },
    { name: 'gamlak vakna', isChosen: false, key: 'vhunmzzHwaTmmAGY', isPickup: false },
    { name: 'thukhente', isChosen: false, key: 'vxKBbpDwTdffypZQo', isPickup: false },
    { name: 'ezra', isChosen: false, key: 'wCiYokVouzqFQQIh', isPickup: false },
    { name: 'galati', isChosen: false, key: 'wiYNpNPlqojFqqtUN', isPickup: false },
    { name: 'korin nihna', isChosen: false, key: 'xsOvylGNZdTUcnJM', isPickup: false },
    { isChosen: false, name: 'kahla', key: 'yiwCzApKuYKluLkpXCeK', isPickup: false },
    { isChosen: false, name: 'paunak', key: 'zMUrahZuoognHhNrOI', isPickup: false },
    { isChosen: false, name: 'thesalon masa', key: 'zcXxdreaquBOyFEW', isPickup: false },
    { isChosen: false, name: 'nehemiah', key: 'zvsEfbbJjyRJIBcgwU', isPickup: false }
]